import type { MetadataRoute } from "next";

const BASE_URL = "https://www.quickfigure.net";

export default function sitemap(): MetadataRoute.Sitemap {
  const locales = ["en", "ko"] as const;
  const routes = [
    "",
    "/tools/word-counter",
    "/tools/case-converter",
    "/tools/lorem-ipsum-generator",
    "/tools/password-generator",
    "/tools/json-formatter",
    "/tools/base64-encoder-decoder",
    "/tools/compound-interest-calculator",
    "/tools/mortgage-calculator",
    "/tools/retirement-calculator",
    "/tools/emergency-fund-calculator",
    "/tools/bmi-calculator",
    "/tools/calorie-calculator",
    "/tools/age-calculator",
    "/tools/symbol-copy-paste",
    "/tools/qr-code-generator",
    "/tools/color-picker",
    "/tools/freelancer-tax-calculator",
    "/tools/salary-calculator",
    "/tools/loan-calculator",
    "/tools/unit-converter",
    "/tools/percentage-calculator",
    "/tools/vat-calculator",
    "/tools/severance-calculator",
    "/tools/rent-conversion-calculator",
    "/tools/area-converter",
    "/tools/dday-calculator",
    "/tools/gpa-calculator",
    "/tools/sleep-calculator",
    "/tools/alcohol-calculator",
    "/tools/date-calculator",
    "/tools/timer",
    "/tools/random-number-generator",
    "/tools/hourly-wage-calculator",
    "/tools/body-fat-calculator",
    "/tools/text-diff",
    "/tools/markdown-editor",
    "/tools/discount-calculator",
    "/tools/electricity-calculator",
    "/tools/image-resizer",
    "/tools/pdf-merger",
    "/tools/weekly-holiday-pay-calculator",
    "/tools/annual-leave-calculator",
    "/tools/unemployment-calculator",
    "/tools/acquisition-tax-calculator",
    "/tools/income-tax-calculator",
    "/tools/image-compressor",
    "/tools/image-to-pdf",
    "/tools/pdf-splitter",
    "/tools/pdf-to-word",
    "/tools/word-to-pdf",
    "/tools/pdf-compressor",
    "/tools/pdf-to-jpg",
    "/tools/image-converter",
    "/tools/car-tax-calculator",
    "/tools/capital-gains-tax-calculator",
    "/tools/loan-comparison-calculator",
    "/tools/inheritance-tax-calculator",
    "/tools/dsr-calculator",
    "/tools/accident-settlement-calculator",
    "/tools/national-pension-calculator",
    "/tools/excel-merge",
    "/tools/image-upscaler",
    "/tools/image-cropper",
    "/tools/image-kb-resizer",
    "/tools/image-watermark",
    "/tools/currency-converter",
    "/tools/css-gradient-generator",
    "/tools/excel-to-pdf",
    "/tools/gif-maker",
    "/tools/hash-generator",
    "/tools/image-rotate",
    "/tools/image-to-svg",
    "/tools/jeonse-vs-wolse-calculator",
    "/tools/ladder-game",
    "/tools/pdf-to-excel",
    "/tools/regex-tester",
    "/tools/roi-calculator",
    "/tools/schedule-finder",
    "/tools/typing-speed-test",
    "/tools/url-encoder-decoder",
    "/tools/uuid-generator",
    "/tools/weekly-pay-calculator",
    "/tools/world-clock",
    "/tools/year-end-tax-calculator",
    "/blog",
    "/blog/how-to-count-words-in-essay",
    "/blog/json-formatting-best-practices",
    "/blog/how-to-create-strong-passwords",
    "/blog/understanding-base64-encoding",
    "/blog/text-case-conversion-guide",
    "/blog/compound-interest-calculator-guide",
    "/blog/mortgage-calculator-guide",
    "/blog/bmi-calculator-guide",
    "/blog/retirement-savings-calculator-guide",
    "/blog/lorem-ipsum-history-and-usage",
    "/blog/emergency-fund-calculator-guide",
    "/blog/age-calculator-guide",
    "/blog/calorie-calculator-guide",
    "/blog/simple-vs-compound-interest",
    "/blog/how-to-calculate-net-worth",
    "/blog/emergency-fund-how-much-to-save",
    "/blog/pay-off-mortgage-faster",
    "/blog/bmr-vs-bmi-difference",
    "/blog/calories-to-lose-weight",
    "/blog/korean-age-vs-international-age",
    "/blog/copy-paste-symbols-special-characters",
    "/blog/how-to-create-qr-code-free",
    "/blog/hex-to-rgb-color-converter-guide",
    "/blog/freelancer-tax-calculator-guide",
    "/blog/salary-calculator-guide",
    "/blog/loan-calculator-guide",
    "/blog/unit-converter-guide",
    "/blog/percentage-calculator-guide",
    "/blog/salary-guide",
    "/blog/vat-guide",
    "/blog/severance-guide",
    "/blog/rent-conversion-guide",
    "/blog/area-guide",
    "/blog/wage-guide",
    "/blog/body-fat-guide",
    "/blog/electricity-guide",
    "/blog/pomodoro-guide",
    "/blog/markdown-guide",
    "/blog/dday-guide",
    "/blog/gpa-guide",
    "/blog/sleep-guide",
    "/blog/alcohol-guide",
    "/blog/date-guide",
    "/blog/weekly-pay-guide",
    "/blog/annual-leave-guide",
    "/blog/unemployment-guide",
    "/blog/acquisition-tax-guide",
    "/blog/income-tax-guide",
    "/blog/image-upscale-guide",
    "/blog/image-crop-guide",
    "/blog/image-kb-guide",
    "/blog/watermark-guide",
    "/blog/currency-converter-exchange-rate-guide",
    "/blog/accident-settlement-guide",
    "/blog/base64-encoding-guide",
    "/blog/capital-gains-guide",
    "/blog/capital-gains-tax-guide",
    "/blog/car-insurance-comparison-2026",
    "/blog/car-tax-guide",
    "/blog/character-count-guide",
    "/blog/color-picker-guide",
    "/blog/credit-score-improvement-guide",
    "/blog/css-gradient-guide",
    "/blog/dsr-guide",
    "/blog/excel-merge-guide",
    "/blog/excel-to-pdf-conversion-guide",
    "/blog/freelancer-tax-guide",
    "/blog/hash-generator-guide",
    "/blog/how-to-make-gif-from-images",
    "/blog/how-to-rotate-images-online",
    "/blog/image-to-vector-svg-complete-guide",
    "/blog/inheritance-tax-guide",
    "/blog/jeonse-vs-wolse-guide",
    "/blog/json-formatter-guide",
    "/blog/ladder-game-online-guide",
    "/blog/loan-comparison-guide",
    "/blog/mortgage-refinance-guide-2026",
    "/blog/national-pension-guide",
    "/blog/pdf-compress-guide",
    "/blog/pdf-to-excel-conversion-guide",
    "/blog/pdf-to-word-guide",
    "/blog/personal-rehabilitation-guide",
    "/blog/policy-fund-guide",
    "/blog/regex-tester-guide",
    "/blog/roi-calculator-investment-guide",
    "/blog/schedule-finder-meeting-time-guide",
    "/blog/small-business-policy-fund-2026",
    "/blog/special-characters-for-sns",
    "/blog/special-characters-keyboard-shortcut",
    "/blog/text-diff-guide",
    "/blog/typing-speed-test-guide",
    "/blog/url-encoder-guide",
    "/blog/uuid-generator-guide",
    "/blog/word-counter-guide",
    "/blog/world-clock-guide",
    "/blog/world-time-converter-guide",
    "/blog/year-end-tax-guide",
    "/about",
    "/contact",
    "/privacy-policy",
    "/terms-of-service",
  ];

  const entries: MetadataRoute.Sitemap = [];

  for (const route of routes) {
    for (const locale of locales) {
      entries.push({
        url: `${BASE_URL}/${locale}${route}`,
        lastModified: new Date(),
        changeFrequency: route === "" ? "weekly" : "monthly",
        priority: route === "" ? 1 : route.startsWith("/tools") ? 0.9 : 0.5,
        alternates: {
          languages: {
            en: `${BASE_URL}/en${route}`,
            ko: `${BASE_URL}/ko${route}`,
          },
        },
      });
    }
  }

  return entries;
}
