import type { MetadataRoute } from "next";

const BASE_URL = "https://quickfigure.net";

export default function sitemap(): MetadataRoute.Sitemap {
  const locales = ["en", "ko"];
  const routes = [
    "",
    "/tools/word-counter",
    "/tools/case-converter",
    "/tools/lorem-ipsum-generator",
    "/tools/password-generator",
    "/tools/json-formatter",
    "/tools/base64-encoder-decoder",
    "/tools/compound-interest-calculator",
    "/tools/mortgage-calculator",
    "/tools/retirement-calculator",
    "/tools/emergency-fund-calculator",
    "/tools/bmi-calculator",
    "/tools/calorie-calculator",
    "/tools/age-calculator",
    "/tools/symbol-copy-paste",
    "/tools/qr-code-generator",
    "/tools/color-picker",
    "/tools/freelancer-tax-calculator",
    "/tools/salary-calculator",
    "/tools/loan-calculator",
    "/tools/unit-converter",
    "/tools/percentage-calculator",
    "/tools/vat-calculator",
    "/tools/severance-calculator",
    "/tools/rent-conversion-calculator",
    "/tools/area-converter",
    "/tools/dday-calculator",
    "/tools/gpa-calculator",
    "/tools/sleep-calculator",
    "/tools/alcohol-calculator",
    "/tools/date-calculator",
    "/tools/timer",
    "/tools/random-number-generator",
    "/tools/hourly-wage-calculator",
    "/tools/body-fat-calculator",
    "/tools/text-diff",
    "/tools/markdown-editor",
    "/tools/discount-calculator",
    "/tools/electricity-calculator",
    "/tools/image-resizer",
    "/tools/pdf-merger",
    "/tools/weekly-holiday-pay-calculator",
    "/tools/annual-leave-calculator",
    "/tools/unemployment-calculator",
    "/tools/acquisition-tax-calculator",
    "/tools/income-tax-calculator",
    "/tools/image-compressor",
    "/tools/image-to-pdf",
    "/tools/pdf-splitter",
    "/tools/pdf-to-word",
    "/tools/word-to-pdf",
    "/tools/pdf-compressor",
    "/tools/pdf-to-jpg",
    "/tools/image-converter",
    "/tools/car-tax-calculator",
    "/tools/capital-gains-tax-calculator",
    "/tools/loan-comparison-calculator",
    "/tools/inheritance-tax-calculator",
    "/tools/dsr-calculator",
    "/tools/accident-settlement-calculator",
    "/tools/national-pension-calculator",
    "/tools/excel-merge",
    "/tools/image-upscaler",
    "/tools/image-cropper",
    "/tools/image-kb-resizer",
    "/tools/image-watermark",
    "/blog",
    "/blog/how-to-count-words-in-essay",
    "/blog/json-formatting-best-practices",
    "/blog/how-to-create-strong-passwords",
    "/blog/understanding-base64-encoding",
    "/blog/text-case-conversion-guide",
    "/blog/compound-interest-calculator-guide",
    "/blog/mortgage-calculator-guide",
    "/blog/bmi-calculator-guide",
    "/blog/retirement-savings-calculator-guide",
    "/blog/lorem-ipsum-history-and-usage",
    "/blog/emergency-fund-calculator-guide",
    "/blog/age-calculator-guide",
    "/blog/calorie-calculator-guide",
    "/blog/simple-vs-compound-interest",
    "/blog/how-to-calculate-net-worth",
    "/blog/emergency-fund-how-much-to-save",
    "/blog/pay-off-mortgage-faster",
    "/blog/bmr-vs-bmi-difference",
    "/blog/calories-to-lose-weight",
    "/blog/korean-age-vs-international-age",
    "/blog/copy-paste-symbols-special-characters",
    "/blog/how-to-create-qr-code-free",
    "/blog/hex-to-rgb-color-converter-guide",
    "/blog/freelancer-tax-calculator-guide",
    "/blog/salary-calculator-guide",
    "/blog/loan-calculator-guide",
    "/blog/unit-converter-guide",
    "/blog/percentage-calculator-guide",
    "/blog/salary-guide",
    "/blog/vat-guide",
    "/blog/severance-guide",
    "/blog/rent-conversion-guide",
    "/blog/area-guide",
    "/blog/wage-guide",
    "/blog/body-fat-guide",
    "/blog/electricity-guide",
    "/blog/pomodoro-guide",
    "/blog/markdown-guide",
    "/blog/dday-guide",
    "/blog/gpa-guide",
    "/blog/sleep-guide",
    "/blog/alcohol-guide",
    "/blog/date-guide",
    "/blog/weekly-pay-guide",
    "/blog/annual-leave-guide",
    "/blog/unemployment-guide",
    "/blog/acquisition-tax-guide",
    "/blog/income-tax-guide",
    "/blog/image-upscale-guide",
    "/blog/image-crop-guide",
    "/blog/image-kb-guide",
    "/about",
    "/contact",
    "/privacy-policy",
    "/terms-of-service",
  ];

  const entries: MetadataRoute.Sitemap = [];

  for (const locale of locales) {
    for (const route of routes) {
      entries.push({
        url: `${BASE_URL}/${locale}${route}`,
        lastModified: new Date(),
        changeFrequency: route === "" ? "weekly" : "monthly",
        priority: route === "" ? 1 : route.startsWith("/tools") ? 0.9 : 0.5,
      });
    }
  }

  return entries;
}
