import type { MetadataRoute } from "next";

const BASE_URL = "https://www.quickfigure.net";

export default function sitemap(): MetadataRoute.Sitemap {
  const locales = ["en", "ko"] as const;
  const routes = [
    "",
    "/tools/word-counter",
    "/tools/case-converter",
    "/tools/lorem-ipsum-generator",
    "/tools/password-generator",
    "/tools/json-formatter",
    "/tools/base64-encoder-decoder",
    "/tools/compound-interest-calculator",
    "/tools/mortgage-calculator",
    "/tools/retirement-calculator",
    "/tools/emergency-fund-calculator",
    "/tools/bmi-calculator",
    "/tools/calorie-calculator",
    "/tools/age-calculator",
    "/tools/symbol-copy-paste",
    "/tools/qr-code-generator",
    "/tools/color-picker",
    "/tools/freelancer-tax-calculator",
    "/tools/salary-calculator",
    "/tools/loan-calculator",
    "/tools/unit-converter",
    "/tools/percentage-calculator",
    "/tools/vat-calculator",
    "/tools/severance-calculator",
    "/tools/rent-conversion-calculator",
    "/tools/area-converter",
    "/tools/dday-calculator",
    "/tools/gpa-calculator",
    "/tools/sleep-calculator",
    "/tools/alcohol-calculator",
    "/tools/date-calculator",
    "/tools/timer",
    "/tools/random-number-generator",
    "/tools/hourly-wage-calculator",
    "/tools/body-fat-calculator",
    "/tools/text-diff",
    "/tools/markdown-editor",
    "/tools/discount-calculator",
    "/tools/electricity-calculator",
    "/tools/image-resizer",
    "/tools/pdf-merger",
    "/tools/weekly-holiday-pay-calculator",
    "/tools/annual-leave-calculator",
    "/tools/unemployment-calculator",
    "/tools/acquisition-tax-calculator",
    "/tools/income-tax-calculator",
    "/tools/image-compressor",
    "/tools/image-to-pdf",
    "/tools/pdf-splitter",
    "/tools/pdf-to-word",
    "/tools/word-to-pdf",
    "/tools/pdf-compressor",
    "/tools/pdf-to-jpg",
    "/tools/image-converter",
    "/tools/car-tax-calculator",
    "/tools/capital-gains-tax-calculator",
    "/tools/loan-comparison-calculator",
    "/tools/inheritance-tax-calculator",
    "/tools/dsr-calculator",
    "/tools/accident-settlement-calculator",
    "/tools/national-pension-calculator",
    "/tools/excel-merge",
    "/tools/image-upscaler",
    "/tools/image-cropper",
    "/tools/image-kb-resizer",
    "/tools/image-watermark",
    "/tools/currency-converter",
    "/tools/css-gradient-generator",
    "/tools/excel-to-pdf",
    "/tools/gif-maker",
    "/tools/hash-generator",
    "/tools/image-rotate",
    "/tools/image-to-svg",
    "/tools/jeonse-vs-wolse-calculator",
    "/tools/ladder-game",
    "/tools/pdf-to-excel",
    "/tools/regex-tester",
    "/tools/roi-calculator",
    "/tools/schedule-finder",
    "/tools/typing-speed-test",
    "/tools/url-encoder-decoder",
    "/tools/uuid-generator",
    "/tools/weekly-pay-calculator",
    "/tools/world-clock",
    "/tools/year-end-tax-calculator",
    "/about",
    "/contact",
    "/privacy-policy",
    "/terms-of-service",
  ];

  const entries: MetadataRoute.Sitemap = [];

  for (const route of routes) {
    for (const locale of locales) {
      entries.push({
        url: `${BASE_URL}/${locale}${route}`,
        lastModified: new Date(),
        changeFrequency: route === "" ? "weekly" : "monthly",
        priority: route === "" ? 1 : route.startsWith("/tools") ? 0.9 : 0.5,
        alternates: {
          languages: {
            en: `${BASE_URL}/en${route}`,
            ko: `${BASE_URL}/ko${route}`,
          },
        },
      });
    }
  }

  return entries;
}
